---
- name: Set up wp-config - "/var/www/{{ http_host }}/wordpress/wp-config.php"
  template:
    src: "templates/wp-config.php.j2"
    dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"
  tags: [wordpress]
#
#
#
#- name: Copy sample config file
#  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php
#
#- name: Update Wordpress config file
#  lineinfile:
#    path: /var/www/wordpress/wp-config.php
#    regexp: "{{item.regexp}}"
#    line: "{{item.line}}"
#  with_items:
#    - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define( 'DB_NAME', 'wordpress' );"}
#    - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define( 'DB_USER', 'wpuser' );"}
#    - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define( 'DB_PASSWORD', 'wpuser_password_replace_with_your_own' );"}
#
